### ISSUE TITLE
Can't configure devices?

### ISSUE THREAD

**Issue by SanZamoyski** [DIYBookScanner/spreads#228] opened 2016-04-19 15:18 UTC
Hi!

I can not get it to work, i get this error while using Spreads Wizard (gui):

```
spread gui
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 
KGlobal::locale(): Warning your global KLocale is being recreated with a valid main component instead of a fake component, this usually means you tried to call i18n related functions before your main component was created. You should not do that since it most likely will not work
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/gui/gui.py", line 235, in validatePage
    wizard.workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 875, in prepare_capture
    "Target page for at least one of the devices could not be"
spreads.util.DeviceException: Target page for at least one of the devices could not bedetermined, please run 'spread configure' to configure yourdevices.
```

Reconfigured spread multiple times, but still nothing...

Tried as root too. _spread configure_ works fine (even focus), but not with gui.

**Comment by jbaiter** [comment] 2016-04-19 16:12
Does capturing images from the command-line work?
Which camera driver are you using with which camera model?
Can you try running both the GUI and the CLI with the '--verbose' flag (has to be passed in before the respective subcommand)?

**Comment by SanZamoyski** [comment] 2016-04-19 16:21
Well, i messed around somehow and i'm getting this:

`san@sammie-mint:/run/shm > sudo pip install spreads
Downloading/unpacking spreads
  Downloading spreads-0.4.1.tar.gz (43kB): 43kB downloaded
  Running setup.py (path:/tmp/pip_build_root/spreads/setup.py) egg_info for package spreads
    
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.5 in /usr/lib/python2.7/dist-packages (from spreads)
Requirement already satisfied (use --upgrade to upgrade): pyusb>=1.0.0a3 in /usr/local/lib/python2.7/dist-packages (from spreads)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /usr/local/lib/python2.7/dist-packages (from spreads)
Requirement already satisfied (use --upgrade to upgrade): Wand>=0.3.1 in /usr/local/lib/python2.7/dist-packages (from spreads)
Requirement already satisfied (use --upgrade to upgrade): stevedore>=0.9.1 in /usr/local/lib/python2.7/dist-packages (from spreads)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.1.4 in /usr/local/lib/python2.7/dist-packages (from spreads)
Requirement already satisfied (use --upgrade to upgrade): pbr>=1.6 in /usr/local/lib/python2.7/dist-packages (from stevedore>=0.9.1->spreads)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from stevedore>=0.9.1->spreads)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from stevedore>=0.9.1->spreads)
Installing collected packages: spreads
  Running setup.py install for spreads
    
    changing mode of build/scripts-2.7/spread from 644 to 755
    changing mode of /usr/local/bin/spread to 755
Successfully installed spreads
Cleaning up...
san@sammie-mint:/run/shm > spread 
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/bin/spread", line 39, in <module>
    cli.main()
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 410, in main
    setup_plugin_config(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/plugin.py", line 344, in setup_plugin_config
    pluginmanager = get_pluginmanager(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/plugin.py", line 316, in get_pluginmanager
    name_order=True)
  File "/usr/local/lib/python2.7/dist-packages/stevedore/named.py", line 55, in __init__
    verify_requirements)
TypeError: _load_plugins() takes exactly 4 arguments (5 given)`

Its definietly 0.4.1 version but tried to install 0.4.2 too. Same effect.

**Comment by SanZamoyski** [comment] 2016-04-19 16:38
While installing by pip install spread i get some error (reported here, but with no solution: http://www.diybookscanner.org/forum/viewtopic.php?p=17162&sid=426109553a27314dfefeeec07dacdb0b#p17162).

Installing other way (with and without --verbose):
`spread capture ./
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 262, in capture
    workflow = spreads.workflow.Workflow(config=config, path=path)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 439, in __init__
    self.bag = bagit.Bag(unicode(self.path))
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py", line 100, in __init__
    self.path = os.path.abspath(path)
  File "/usr/lib/python2.7/posixpath.py", line 369, in abspath
    cwd = os.getcwdu()
OSError: [Errno 2] No such file or directory`

GUI:
`spread --verbose gui
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
spreadsplug.gui: Starting GUI
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 
KGlobal::locale(): Warning your global KLocale is being recreated with a valid main component instead of a fake component, this usually means you tried to call i18n related functions before your main component was created. You should not do that since it most likely will not work
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)
spreadsplug.gui: Updating config from widgets for plugin device
spreadsplug.gui: Trying to set key "parallel_capture"
spreadsplug.gui: Setting to "True"
spreadsplug.gui: Trying to set key "upside_down"
spreadsplug.gui: Setting to "False"
spreadsplug.gui: Trying to set key "flip_target_pages"
spreadsplug.gui: Setting to "False"
spreadsplug.gui: Trying to set key "focus_distance"
spreadsplug.gui: Trying to set key "sensitivity"
spreadsplug.gui: Trying to set key "shoot_raw"
spreadsplug.gui: Setting to "False"
spreadsplug.gui: Trying to set key "zoom_level"
spreadsplug.gui: Trying to set key "shutter_speed"
spreadsplug.gui: Setting to "1/25"
spreadsplug.gui: Trying to set key "monochrome"
spreadsplug.gui: Setting to "False"
spreadsplug.gui: Trying to set key "focus_mode"
spreadsplug.gui: Setting to "autofocus_all"
spreadsplug.gui: Trying to set key "whitebalance"
spreadsplug.gui: Setting to "Auto"
spreadsplug.gui: Trying to set key "dpi"
Workflow: Initializing workflow /home/san/Projekty/OCR Machine/
bagit: Adding path /home/san/Projekty/OCR Machine/bag-info.txt to payload
bagit: Adding path /home/san/Projekty/OCR Machine/config.yml to payload
Workflow: Preparing capture.
spreads.plugin: Finding devices for driver "CHDKCameraDevice"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/gui/gui.py", line 235, in validatePage
    wizard.workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 875, in prepare_capture
    "Target page for at least one of the devices could not be"
spreads.util.DeviceException: Target page for at least one of the devices could not bedetermined, please run 'spread configure' to configure yourdevices.`

BTW. spread cleared whole directory i've used for project - uncool!

**Comment by SanZamoyski** [comment] 2016-04-19 16:58
By installing spread by 

i got: sudo pip install git+git://github.com/jbaiter/spreads.git@master

> sudo spread gui
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
> /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Zła wartość
> collect2: error: ld returned 1 exit status
> Error: "/var/tmp/kdecache-san" is owned by uid 1000 instead of uid 0.
> Bus::open: Can not get ibus-daemon's address. 
> IBusInputContext::createInputContext: no connection to ibus-daemon 
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/spreadsplug/gui/gui.py", line 217, in validatePage
>     wizard.workflow.prepare_capture()
>   File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 210, in prepare_capture
>     if any(dev.target_page is None for dev in self.devices):
>   File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 80, in devices
>     self._devices = plugin.get_devices(self.config, force_reload=True)
>   File "/usr/local/lib/python2.7/dist-packages/spreads/plugin.py", line 393, in get_devices
>     devices = list(driver.yield_devices(config['device']))
>   File "/usr/local/lib/python2.7/dist-packages/spreadsplug/dev/chdkcamera.py", line 90, in yield_devices
>     yield cls(config, dev)
>   File "/usr/local/lib/python2.7/dist-packages/spreadsplug/dev/chdkcamera.py", line 104, in __init__
>     usb.util.get_string(device, 256, device.iSerialNumber)
>   File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 318, in get_string
>     raise ValueError("The device does not support the specified langid")
> ValueError: The device does not support the specified langid
>

**Comment by jbaiter** [comment] 2016-04-19 17:14
> BTW. spread cleared whole directory i've used for project - uncool!

That is most definitely more than uncool, basically the worst thing a program could do :-/
I'm really sorry :cold_sweat: 

I think this was caused by a lack of documentation on my part: When you specify a directory for capturing, you should give the full name of the project directory, i.e. `spread capture ./my-project`.
If there are already files in the specified directory and those files/directories are not laid out in the BagIt structure that spreads uses, it will copy them to a temporary path, then remove the old directory and create a new directory with the old files in its place. So in theory all your files should still be in `./`, but it could be that this failed since spreads removed the working directory, and then "./" could no longer be resolved. I will probably remove this whole "convert to BagIt structure" functionality completely, it was mainly intended for users of an older version to migrate their projects.
I hope you did not lose any important files!

Now, to your main problem: **You're installing `spreads` from the wrong location!** The official repository is **DIYBookScanner/spreads** and not *jbaiter/spreads*! The latter is a personal fork of mine that is far behind the current codebase.

Please install spreads from the proper repository and then run `spread --verbose configure` from the command-line and post the output here. That way I can see if your problem starts already with configuration or if it's something else further along in the process.

**Comment by SanZamoyski** [comment] 2016-04-19 18:57
> I hope you did not lose any important files!
me too!

Installed by: sudo pip install git+git://github.com/DIYBookScanner/spreads.git@master

> san@sammie-mint:~ > spread -V
> spreads 0.5git20160419.ff6a
> 
> Licensed under the terms of the GNU Affero General Public License 3.0.
> (C) 2013-2014 Johannes Baiter <johannes.baiter@gmail.com>
> For a complete list of contributors see:
> https://github.com/DIYBookScanner/spreads/graphs/contributors

> san@sammie-mint:~ > spread --verbose configure
> Please select a device driver from the following list:
>   [0]: Keep current (chdkcamera)
>   [1]: gphoto2camera
>   [2]: chdkcamera
>   [3]: dummy
>   [4]: None
> Select a driver: 2
> Selected "chdkcamera" as device driver
> Please select your desired plugins from the following list:
>     1: autorotate
>     2: djvubind
>   x 3: gui
>     4: hidtrigger
>     5: intervaltrigger
>     6: pdfbeads
>     7: scantailor
>     8: tesseract
>     9: web
> Select a plugin (or hit enter to finish): 
> Do you want to configure the target_page of your devices?
> (Required for shooting with two devices) [y/N]: 
> Do you want to setup the focus for your cameras? [y/N]: 
> Configuration file written to '/home/san/.config/spreads/config.yaml'
> san@sammie-mint:~ > sudo spread --verbose gui 
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
> /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Zła wartość
> collect2: error: ld returned 1 exit status
> usage: spread [-h] [-V] [--loglevel <info/critical/error/warning/debug>]
>               [--logfile <str>] [--no-convert-old] [--no-verbose]
>               {wizard,configure,guiconfigure,capture,postprocess,output,gui}
>               ...
> spread: error: unrecognized arguments: --verbose
> san@sammie-mint:~ > sudo spread gui          
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
> /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Zła wartość
> collect2: error: ld returned 1 exit status
> spreadsplug.gui: Starting GUI
> Error: "/var/tmp/kdecache-san" is owned by uid 1000 instead of uid 0.
> Bus::open: Can not get ibus-daemon's address. 
> IBusInputContext::createInputContext: no connection to ibus-daemon 
> spreadsplug.gui: Updating config from widgets for plugin device
> spreadsplug.gui: Trying to set key "parallel_capture"
> spreadsplug.gui: Setting to "True"
> spreadsplug.gui: Trying to set key "upside_down"
> spreadsplug.gui: Setting to "False"
> spreadsplug.gui: Trying to set key "flip_target_pages"
> spreadsplug.gui: Setting to "False"
> spreadsplug.gui: Trying to set key "focus_distance"
> spreadsplug.gui: Trying to set key "sensitivity"
> spreadsplug.gui: Trying to set key "shoot_raw"
> spreadsplug.gui: Setting to "False"
> spreadsplug.gui: Trying to set key "zoom_level"
> spreadsplug.gui: Trying to set key "shutter_speed"
> spreadsplug.gui: Setting to "1/25"
> spreadsplug.gui: Trying to set key "monochrome"
> spreadsplug.gui: Setting to "False"
> spreadsplug.gui: Trying to set key "focus_mode"
> spreadsplug.gui: Setting to "autofocus_all"
> spreadsplug.gui: Trying to set key "whitebalance"
> spreadsplug.gui: Setting to "Auto"
> spreadsplug.gui: Trying to set key "dpi"
> Workflow: Initializing workflow /home/san/Projekty/OCR Machine/spread
> bagit: Adding path /home/san/Projekty/OCR Machine/spread/bag-info.txt to payload
> bagit: Adding path /home/san/Projekty/OCR Machine/spread/config.yml to payload
> Workflow: Preparing capture.
> spreads.plugin: Finding devices for driver "CHDKCameraDevice"
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/spreadsplug/gui/gui.py", line 235, in validatePage
>     wizard.workflow.prepare_capture()
>   File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 875, in prepare_capture
>     "Target page for at least one of the devices could not be"
> spreads.util.DeviceException: Target page for at least one of the devices could not bedetermined, please run 'spread configure' to configure yourdevices.

Might it be I made something wrong while running (installing?) chdk on my camera? I'm quite sure it's quite impossible, but...

**Comment by jbaiter** [comment] 2016-04-19 19:31
Those errors you're getting are due to a badly set LUA_PATH variable. Here's the command from the `chdkptp` documentation: `LUA_PATH="/path/to/chdkptp/lua/?.lua" /path/to/chdkptp`
As for CHDK on your camera, can you see the CHDK logo when starting the camera?

**Comment by SanZamoyski** [comment] 2016-04-19 19:53
after `export LUA_PATH="/usr/local/lib/chdkptp/lua/?.lua"`
chdkptp works:

> san@sammie-mint:/dev/shm > /usr/local/lib/chdkptp/chdkptp                                            
> ___> quit

while spread, even with LUA_PATH does not:

> san@sammie-mint:/dev/shm > LUA_PATH="/usr/local/lib/chdkptp/lua/?.lua" sudo spread gui
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
> /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Zła wartość
> collect2: error: ld returned 1 exit status
> spreadsplug.gui: Starting GUI
> Error: "/var/tmp/kdecache-san" is owned by uid 1000 instead of uid 0.
> Bus::open: Can not get ibus-daemon's address. 
> IBusInputContext::createInputContext: no connection to ibus-daemon 
> spreadsplug.gui: Updating config from widgets for plugin device
> spreadsplug.gui: Trying to set key "parallel_capture"
> spreadsplug.gui: Setting to "True"
> spreadsplug.gui: Trying to set key "upside_down"
> spreadsplug.gui: Setting to "False"
> spreadsplug.gui: Trying to set key "flip_target_pages"
> spreadsplug.gui: Setting to "False"
> spreadsplug.gui: Trying to set key "focus_distance"
> spreadsplug.gui: Trying to set key "sensitivity"
> spreadsplug.gui: Trying to set key "shoot_raw"
> spreadsplug.gui: Setting to "False"
> spreadsplug.gui: Trying to set key "zoom_level"
> spreadsplug.gui: Trying to set key "shutter_speed"
> spreadsplug.gui: Setting to "1/25"
> spreadsplug.gui: Trying to set key "monochrome"
> spreadsplug.gui: Setting to "False"
> spreadsplug.gui: Trying to set key "focus_mode"
> spreadsplug.gui: Setting to "autofocus_all"
> spreadsplug.gui: Trying to set key "whitebalance"
> spreadsplug.gui: Setting to "Auto"
> spreadsplug.gui: Trying to set key "dpi"
> Workflow: Initializing workflow /home/san/Projekty/OCR Machine/spread
> bagit: Adding path /home/san/Projekty/OCR Machine/spread/bag-info.txt to payload
> bagit: Adding path /home/san/Projekty/OCR Machine/spread/config.yml to payload
> Workflow: Preparing capture.
> spreads.plugin: Finding devices for driver "CHDKCameraDevice"
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/spreadsplug/gui/gui.py", line 235, in validatePage
>     wizard.workflow.prepare_capture()
>   File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 875, in prepare_capture
>     "Target page for at least one of the devices could not be"
> spreads.util.DeviceException: Target page for at least one of the devices could not bedetermined, please run 'spread configure' to configure yourdevices.

shouldn't it be easier?

**Comment by jbaiter** [comment] 2016-04-19 20:03
Just opening `chdkptp` won't tell you if CHDK is working on your camera and the computer <-> camera communication is working properly. Please read the chdkptp manual on the relevant commands.
Also, please check if your camera boots CHDK properly (i.e. can you see the logo at startup, see my previous answer) and if the `OWN.TXT` file exists on the SD card.

**Comment by SanZamoyski** [comment] 2016-04-19 20:12
It definietly works (sorry, forgot to answer Your question - yes, i do see logo):

> ___> c
> connected: Canon PowerShot A480, max packet size 64
> con> imls
> Thu Apr 14 14:22:44 2016    2378716 A/DCIM/104CANON/IMG_0005.JPG
> (...)
> Tue Apr 19 14:30:04 2016    1493854 A/DCIM/104CANON/IMG_0028.JPG

**Comment by SanZamoyski** [comment] 2016-04-20 08:24
And how about this one (while configuring):

> spreads.plugin: Finding devices for driver "CHDKCameraDevice"
> open_camera_dev_usb: ptp_opensession failed 0x2ff
> Device status OK

You wrote somewhere:
> This happens when for some reason the driver loses connection to the camera, it will then try to re-connect up to two times, these are the messages from that from the low-level USB code.
> Does this break the workflow in your case? Do you have to restart the cameras manually?

And it seems for me that answer is no. There is no problem with connection at all (i belive).

**Comment by jbaiter** [comment] 2016-04-20 16:54
Yes, it seems that way.

> Also, please check [...] if the OWN.TXT file exists on the SD card (see also my previous answer).

Could you do that please? This file records for which side of the page spread the camera is responsible. It should  be created during the `configure` step.

**Comment by SanZamoyski** [comment] 2016-04-20 20:42
Will do!
...but unluckily i've left camera at university - so i'll do it in about 12h...
anyway i've been configurint only one camera at the time - is that wrong?

**Comment by SanZamoyski** [comment] 2016-04-21 08:47
No such file.

**Comment by jbaiter** [comment] 2016-04-21 12:31
> anyway i've been configurint only one camera at the time - is that wrong?

Ah, there we go, that's the issue.
The software is currently designed for DIYBookScanner-typish scanners, which work with two cameras, one for each side of the page spread. Since you only have one camera, you probably (logically) skipped the "Do you want to set the target page..." part of the `configure` step.
I just committed a change that should allow for single-camera usage, but keep in mind that this is not a use case that was tested, so depending on your choice of interface you could run into a few more issues. I'd recommend the command-line interface, it's the most bare-bones one and should work as-is.

**Comment by SanZamoyski** [comment] 2016-04-21 13:50
That might be the case. Today i've configured it for two cameras and it works just fine.
Thank You.

**Comment by jbaiter** [comment] 2016-04-21 13:58
Thank you, that was definitely a bug in the code!

**Closed by jbaiter** 2016-04-21 13:58 UTC
