### ISSUE TITLE
TypeError: argument of type 'int' is not iterable,

### ISSUE THREAD

**Issue by dropshot94** [DIYBookScanner/spreads#153] opened 2015-01-01 20:51 UTC
I'm new to spreads, and am having a problem in setup. I have two Canon A2200s with CHDK setup. After running spread configure from an SSH session, I tried to capture images with a workflow. I received the error copied below ("argument of type 'int' is not iterable").

I hope you can help.

Thanks.

Edit: I'm using Spreadpi20141128 (the most recent build) on a Raspberry Pi B+
The A2200s are using CHDK version a2200-100d-1.3.0-3860-full.zip 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 929, in prepare_capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 864, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 120, in check_futures_exceptions
    raise exc
TypeError: argument of type 'int' is not iterable

```

**Comment by jbaiter** [comment] 2015-01-04 14:45
Did you manage to solve the issue by yourself? If so, could you explain what you did so that other users can benefit from it too and I can maybe make the documentation clearer on what to do? :-)

**Comment by dropshot94** [comment] 2015-01-04 21:09
Johannes,

I thought I had solved the problem, but it turns out that I have not. I've
been trying to narrow down the source of the error by swapping out parts of
my setup. So far, I've:

- used spread on Ubuntu
- plugged the cameras into different USB ports
- used a powered hub for the cameras
- reformatted and reinstalled CHDK on both cameras
- used different cables on the cameras
- tried several different sequences of turning cameras and pi on
- reconfigured spread
- tried manually stopping and then starting spread on the pi (with cameras
on and also with cameras off)

The only time I had success, it was after reinstalling CHDK, but the error
returned during my next session.

So, having (at least I think) eliminated the Pi, the USB connection, the
cables, and the CHDK installation, I think I have at least one faulty
camera. I think that’s plausible because often one of the cameras seems not
to respond to the preparatory commands to begin taking photos.

Canon has the A2200 (refurbished) on sale for US$35, so I've ordered two to
replace my current 2200s. I'll report back when I've tried them.

Of course, I welcome any further suggestions for troubleshooting.

Thank you for following up.

Ed

**Comment by boredland** [comment] 2015-01-11 14:14
Hi,

I've got exactly the same error and no idea how it occured. I get the "TypeError: argument of type 'int' is not iterable" everytime I try to start a Workflow.

**Comment by boredland** [comment] 2015-01-11 17:04
Not really a fix: I different setups, none worked. Finally I took another sd-card and dropped the latest spreadpi on it. Its working now.

**Comment by jbaiter** [comment] 2015-01-11 17:39
OK, so this error is raised in the `prepare_capture` method of the CHDK driver, so most probably the device is returning some unexpected data and the driver doesn't know how to deal with it.
Could both of you re-run with debug logging enabled (`spread --verbose`)? This will log all the data sent from the device and might give us better insight into why this error is occuring.

**Comment by dropshot94** [comment] 2015-01-11 18:34
I also "fixed" the problem the same way. The latest spread-pi seemed to fix
the problem, although I also replaced the cameras at the same time.

**Comment by jbaiter** [comment] 2015-01-12 14:19
OK, then I'll close this for now.

**Comment by listerinepaks** [comment] 2015-01-14 15:56
Seems like I have the same setup and similar issue as above. a2200's in a powered hub from spreadspi 20150113 nightly. For me the issue seems to be related to letting spreads configure setup my focus as manual. It likes a setting around 291. If i setup autofocus_all or autofocus_initial. Then it seems with limited testing to allow me to get in capture mode without the "int not iterable" error.

**Comment by jbaiter** [comment] 2015-01-14 16:07
Thanks for the info, that helped a lot!
I think I located the cause and just pushed a change that might fix it, could you give it a shot?

**Comment by listerinepaks** [comment] 2015-01-14 17:01
i think that fixed it. Thank you!
don't know enough about github. so i kinda kludged the install. manually downloaded the changed file chdkcamera.py. made sure it compiled. tested by setting the focus mode to manual and length to 291. it entered capture mode without any errors. just to make sure i reran "spread configure" which set it to manual focus, restart spread, new workflow, no errors. then i test autofocus_all and autofocus_initial without error as well.

**Closed** 2015-01-14 18:28 UTC
